--[[
This file is part of the mod ConfigUnderLengths that is licensed under the
GNU GPL-3.0. See the file COPYING for a copy of the GNU GPLv3.0.
]]
data:extend({
    {
        name = "config-under-lengths-pipes-1",
        type = "int-setting",
        order = "10",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-pipes-2",
        type = "int-setting",
        order = "11",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-pipes-3",
        type = "int-setting",
        order = "12",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-pipes-4",
        type = "int-setting",
        order = "13",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-pipes-5",
        type = "int-setting",
        order = "14",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-1",
        type = "int-setting",
        order = "20",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-2",
        type = "int-setting",
        order = "21",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-3",
        type = "int-setting",
        order = "22",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-4",
        type = "int-setting",
        order = "23",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-5",
        type = "int-setting",
        order = "24",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-6",
        type = "int-setting",
        order = "25",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-7",
        type = "int-setting",
        order = "26",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-belts-8",
        type = "int-setting",
        order = "27",
        setting_type = "startup",
        minimum_value = -1,
        maximum_value = 254,
        default_value = -1,
    },
    {
        name = "config-under-lengths-debug",
        type = "bool-setting",
        order = "30",
        setting_type = "startup",
        default_value = false,
    },
})
